POST http://localhost:3000/api/cursos/programacion
Content-Type: application/json

{
  "id": 10,
  "titulo": "Aprende Node.js",
  "lenguaje": "javascript",
  "vistas": 3438439,
  "nivel": "basico"
}

###

PUT http://localhost:3000/api/cursos/programacion/2
Content-Type: application/json

{
  "id": 2,
  "titulo": "Aprende Node.js modificado",
  "lenguaje": "javascript",
  "vistas": 111111,
  "nivel": "basico"
}


###

PATCH http://localhost:3000/api/cursos/programacion/2
Content-Type: application/json

{
  "titulo": "Aprende Node.js patcheado"
}

###

DELETE http://localhost:3000/api/cursos/programacion/2
